### ISSUE TITLE
サイコロを振って止めるとフリーズする

### ISSUE THREAD

**Issue by ozegod** [ozegod/GameJam2020Winter#1]
タイトルの通り。以下にまとめておきます。

**既にわかっていること**
- 2回目のスペースを押すとバグる
- PlayerにPlayer.csをattachしてプログラムを実行するとバグる。（アタッチ無しでは正常に動く）
- 2回目にスペースキーを入力してDiseRoll()を実行するタイミングで止まる模様（従ってその後のコードが原因ではない）

**要検証**
- サイコロを振るだけならセーフ？（止める前にバグることもある）
- currentplayerがうまく動いていない？
- そもそもターン切替のコード自体がコピペなのでまだよく理解できてない部分があるかもしれない（特にserializefield）

**Comment by anonymous-gigaflops** [comment]
ひとまずフリーズはしなくなったのでClose
